name: PHP CS Check

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Setup PHP"
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Make phpcs Executable
      run: chmod +x vendor/bin/phpcs

    # - name: Detecting PHP Code Standards Violations
    #   run: composer run-script phpcs

    - name: Detecting PHP Code Standards Violations
      run: ./vendor/bin/php-cs-fixer fix app --dry-run
