name: PHP CS Check

on:
  push:
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate Composer.json and composer.lock
      run: composer update

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Make phpcs Executable
      run: chmod +x vendor/bin/phpcs

    - name: Detecting PHP Code Standards Violations
      run: composer run-script phpcs
